In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('/content/exchange_rate.csv')

In [4]:
data.head()

,Currency,2022-10-09,2022-10-08,2022-10-07,2022-10-06,2022-10-05,2022-10-04,2022-10-03,2022-10-02,2022-10-01,...,2021-10-19,2021-10-18,2021-10-17,2021-10-16,2021-10-15,2021-10-14,2021-10-13,2021-10-12,2021-10-11,2021-10-10
0,EUR,1.026575,1.026655,1.022323,1.018879,1.013599,1.002286,1.019629,1.020184,1.020042,...,0.859692,0.861496,0.861967,0.862110,0.862511,0.862679,0.864266,0.866563,0.864130,0.864361
1,GBP,0.901799,0.901422,0.899852,0.895888,0.887287,0.873880,0.887196,0.896315,0.895387,...,0.724328,0.728614,0.728405,0.728962,0.726917,0.730706,0.732944,0.735178,0.733981,0.734565
2,INR,82.815406,82.831603,82.598080,82.114846,81.646995,81.451499,81.564234,81.592623,81.569652,...,75.100380,75.314305,75.038254,75.066698,74.972446,75.068794,75.321664,75.458774,75.440350,75.163641
3,AUD,1.567035,1.567298,1.564782,1.557739,1.547420,1.540775,1.538110,1.556323,1.559839,...,1.336667,1.348544,1.348409,1.348377,1.348582,1.347732,1.356789,1.358192,1.357285,1.369552
4,CAD,1.375648,1.373856,1.369535,1.372447,1.366558,1.355457,1.365132,1.384204,1.383634,...,1.235378,1.236399,1.237029,1.237815,1.238766,1.236370,1.244922,1.244235,1.245718,1.247054

In [5]:
data = data.T

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366 entries, Currency to 2021-10-10
Data columns (total 53 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       366 non-null    object
 1   1       366 non-null    object
 2   2       366 non-null    object
 3   3       366 non-null    object
 4   4       366 non-null    object
 5   5       366 non-null    object
 6   6       366 non-null    object
 7   7       366 non-null    object
 8   8       366 non-null    object
 9   9       366 non-null    object
 10  10      366 non-null    object
 11  11      366 non-null    object
 12  12      366 non-null    object
 13  13      366 non-null    object
 14  14      366 non-null    object
 15  15      366 non-null    object
 16  16      366 non-null    object
 17  17      366 non-null    object
 18  18      366 non-null    object
 19  19      366 non-null    object
 20  20      366 non-null    object
 21  21      366 non-null    object
 22  22      366 non-null    object
 23  23      366 non-null    object
 24  24      366 non-null    object
 25  25      366 non-null    object
 26  26      366 non-null    object
 27  27      366 non-null    object
 28  28      366 non-null    object
 29  29      366 non-null    object
 30  30      366 non-null    object
 31  31      366 non-null    object
 32  32      366 non-null    object
 33  33      366 non-null    object
 34  34      366 non-null    object
 35  35      366 non-null    object
 36  36      366 non-null    object
 37  37      366 non-null    object
 38  38      366 non-null    object
 39  39      366 non-null    object
 40  40      366 non-null    object
 41  41      366 non-null    object
 42  42      366 non-null    object
 43  43      366 non-null    object
 44  44      366 non-null    object
 45  45      366 non-null    object
 46  46      366 non-null    object
 47  47      366 non-null    object
 48  48      366 non-null    object
 49  49      366 non-null    object
 50  50      366 non-null    object
 51  51      366 non-null    object
 52  52      366 non-null    object
dtypes: object(53)
memory usage: 162.5+ KB

In [7]:
data

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
Currency,EUR,GBP,INR,AUD,CAD,SGD,CHF,MYR,JPY,CNY,...,SAR,ZAR,LKR,SEK,TWD,THB,TTD,TRY,AED,VEF
2022-10-09,1.026575,0.901799,82.815406,1.567035,1.375648,1.43311,0.995222,4.651077,145.569646,7.108592,...,3.75,18.005929,364.188388,11.224991,31.753419,37.623741,6.770081,18.570743,3.6725,819495.007127
2022-10-08,1.026655,0.901422,82.831603,1.567298,1.373856,1.433026,0.994566,4.651033,145.362732,7.113716,...,3.75,18.096037,364.220655,11.226735,31.76877,37.623635,6.770388,18.577722,3.6725,819494.936494
2022-10-07,1.022323,0.899852,82.59808,1.564782,1.369535,1.431317,0.991899,4.650129,145.205682,7.116829,...,3.75,18.093471,365.90403,11.174542,31.712074,37.555197,6.78705,18.588653,3.6725,819530.322647
2022-10-06,1.018879,0.895888,82.114846,1.557739,1.372447,1.428843,0.989355,4.637534,144.876758,7.116277,...,3.75,17.929514,365.992277,11.105921,31.550362,37.379236,6.781602,18.591595,3.6725,819396.909491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-14,0.862679,0.730706,75.068794,1.347732,1.23637,1.348588,0.923178,4.155049,113.585427,6.439989,...,3.75,14.789252,201.987127,8.631958,28.058044,33.1583,6.790442,9.194436,3.6725,417644.940426
2021-10-13,0.864266,0.732944,75.321664,1.356789,1.244922,1.352519,0.92589,4.159807,113.485383,6.427541,...,3.75,14.814139,201.020183,8.709849,28.089506,33.206221,6.792244,9.074687,3.6725,415821.67475
2021-10-12,0.866563,0.735178,75.458774,1.358192,1.244235,1.35637,0.930383,4.166568,113.709057,6.448975,...,3.75,14.959827,200.481392,8.772057,28.149673,33.308441,6.797895,9.039674,3.6725,416171.909043
2021-10-11,0.86413,0.733981,75.44035,1.357285,1.245718,1.353632,0.926876,4.170208,113.374375,6.451254,...,3.75,14.959081,201.494573,8.746236,28.035456,33.605925,6.797415,8.976764,3.6725,415414.050643
2021-10-10,0.864361,0.734565,75.163641,1.369552,1.247054,1.355472,0.928016,4.178356,112.316573,6.444076,...,3.75,14.931678,199.843527,8.754745,28.109232,33.864538,6.796685,8.966519,3.6725,425804.29379

In [8]:
data.iloc[1:, :] = data.iloc[1:, :].astype(float)

In [9]:
data_T = data.rename(columns=data.iloc[0]).iloc[1:]

In [10]:
data_T.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365 entries, 2022-10-09 to 2021-10-10
Data columns (total 53 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EUR     365 non-null    object
 1   GBP     365 non-null    object
 2   INR     365 non-null    object
 3   AUD     365 non-null    object
 4   CAD     365 non-null    object
 5   SGD     365 non-null    object
 6   CHF     365 non-null    object
 7   MYR     365 non-null    object
 8   JPY     365 non-null    object
 9   CNY     365 non-null    object
 10  ARS     365 non-null    object
 11  BHD     365 non-null    object
 12  BWP     365 non-null    object
 13  BRL     365 non-null    object
 14  BND     365 non-null    object
 15  BGN     365 non-null    object
 16  CLP     365 non-null    object
 17  COP     365 non-null    object
 18  HRK     365 non-null    object
 19  CZK     365 non-null    object
 20  DKK     365 non-null    object
 21  HKD     365 non-null    object
 22  HUF     365 non-null    object
 23  ISK     365 non-null    object
 24  IDR     365 non-null    object
 25  IRR     365 non-null    object
 26  ILS     365 non-null    object
 27  KZT     365 non-null    object
 28  KRW     365 non-null    object
 29  KWD     365 non-null    object
 30  LYD     365 non-null    object
 31  MUR     365 non-null    object
 32  MXN     365 non-null    object
 33  NPR     365 non-null    object
 34  NZD     365 non-null    object
 35  NOK     365 non-null    object
 36  OMR     365 non-null    object
 37  PKR     365 non-null    object
 38  PHP     365 non-null    object
 39  PLN     365 non-null    object
 40  QAR     365 non-null    object
 41  RON     365 non-null    object
 42  RUB     365 non-null    object
 43  SAR     365 non-null    object
 44  ZAR     365 non-null    object
 45  LKR     365 non-null    object
 46  SEK     365 non-null    object
 47  TWD     365 non-null    object
 48  THB     365 non-null    object
 49  TTD     365 non-null    object
 50  TRY     365 non-null    object
 51  AED     365 non-null    object
 52  VEF     365 non-null    object
dtypes: object(53)
memory usage: 154.0+ KB

In [11]:
data_T.head()

,EUR,GBP,INR,AUD,CAD,SGD,CHF,MYR,JPY,CNY,...,SAR,ZAR,LKR,SEK,TWD,THB,TTD,TRY,AED,VEF
2022-10-09,1.026575,0.901799,82.815406,1.567035,1.375648,1.43311,0.995222,4.651077,145.569646,7.108592,...,3.75,18.005929,364.188388,11.224991,31.753419,37.623741,6.770081,18.570743,3.6725,819495.007127
2022-10-08,1.026655,0.901422,82.831603,1.567298,1.373856,1.433026,0.994566,4.651033,145.362732,7.113716,...,3.75,18.096037,364.220655,11.226735,31.76877,37.623635,6.770388,18.577722,3.6725,819494.936494
2022-10-07,1.022323,0.899852,82.59808,1.564782,1.369535,1.431317,0.991899,4.650129,145.205682,7.116829,...,3.75,18.093471,365.90403,11.174542,31.712074,37.555197,6.78705,18.588653,3.6725,819530.322647
2022-10-06,1.018879,0.895888,82.114846,1.557739,1.372447,1.428843,0.989355,4.637534,144.876758,7.116277,...,3.75,17.929514,365.992277,11.105921,31.550362,37.379236,6.781602,18.591595,3.6725,819396.909491
2022-10-05,1.013599,0.887287,81.646995,1.54742,1.366558,1.42763,0.984197,4.631164,144.743666,7.116289,...,3.75,17.836007,365.990202,10.992073,31.622162,37.508595,6.765191,18.573197,3.6725,818141.148683

In [12]:
import plotly.express as px

fig = px.line(data_T.iloc[:,[2]])
fig.show()